[versions]
androidXAppCompat = "1.7.0"
androidXArch = "2.2.0"
androidXBrowser = "1.8.0"
androidXConstraintLayout = "2.2.0"
androidXCore = "1.15.0"
androidXLifecycle = "2.8.7"
androidx-lifecycle = "2.8.4"
androidXLocalBroadcastManager = "1.1.0"
androidXNavigation = "2.8.5"
androidXSwipeRefreshLayout = "1.1.0"
androidXTestCore = "1.6.1"
androidXTestEspresso = "3.6.1"
androidXTestJunit = "1.2.1"
jsoup = "1.18.3"
junit = "4.13.2"
material = "1.12.0"
mockK = "1.13.13"
okhttp = "4.12.0"
okio = "3.9.1"
retrofit = "2.11.0"
truth = "1.4.4"
leakcanary = "2.14"
gson = "2.11.0"
coroutines = "1.9.0"
coil = "2.7.0"
koinCore = "4.0.0"
koinAndroid = "4.0.0"
spotless = "6.22.0"

agp = "8.10.1"
kotlin = "2.1.10"
kotlinStdlib = "2.1.10"
kotlinTest = "2.1.10"
runner = "1.6.2"
core = "1.6.1"
composeMultiplatform = "1.7.3"
kotlinAndroid = "2.1.0"
androidx-activityCompose = "1.10.1"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidXAppCompat"}
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidXBrowser"}
androidx-arch = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidXArch"}
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidXConstraintLayout"}

androidx-lifecycle-compiler = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "androidXLifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidXLifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidXLifecycle" }

androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidXNavigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidXNavigation" }

androidx-localbroadcastmanager = { group = "androidx.localbroadcastmanager", name = "localbroadcastmanager", version.ref = "androidXLocalBroadcastManager" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "androidXSwipeRefreshLayout" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidXCore" }

androidx-test-core = { group = "androidx.test", name = "core-ktx", version.ref = "androidXTestCore" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidXTestJunit" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidXTestEspresso" }

google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
google-truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

mockk-core = { group = "io.mockk", name = "mockk", version.ref = "mockK" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockK" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

coil = { group = "io.coil-kt", name = "coil", version.ref = "coil"}

square-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
square-log = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
square-okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
square-leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
square-retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
square-retrofit-gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koinCore" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koinCore" }
koin-junit4 = { group = "io.insert-koin", name = "koin-test-junit4", version.ref = "koinCore" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koinAndroid" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
core = { group = "androidx.test", name = "core", version.ref = "core" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid"}
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }