name: Android CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'
      - '!dev*'
  pull_request:
    branches:
      - 'master'
      - 'release*'
      - 'dev'    

jobs:
  test:
    name: Run Build Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Set up environment
      env:
        TEST_ACCOUNT: ${{ secrets.TEST_ACCOUNT }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      shell: bash
      run: echo -e "ACCOUNT=$TEST_ACCOUNT\nPASSWORD=$TEST_PASSWORD" > ./local.properties
      
    - name: Spotless Check
      run: bash ./gradlew spotlessCheck    
      
    - name: Build Test
      run: bash ./gradlew clean assembleStagingDebug

    - name: Unit Test
      run: bash ./gradlew testStagingDebugUnitTest
